export {default as CartPage} from './CartPage'
export {default as CheckOut} from './CheckOut'
export {default as Home} from './Home'
export {default as LoginPage} from './LoginPage'
export {default as SignUpPage} from './SignUpPage'
export {default as ProductDetailPage} from './ProductDetailPage'
export {default as OrderPage} from './OrderPage'
export {default as ErrorPage} from './ErrorPage'